version: '3.8'

services:
  # supersonic_be:
  #   build:
  #     context: .
  #     dockerfile: jdk.8.Dockerfile
  #   environment:
  #     DB_HOST: supersonic_mysql
  #     DB_NAME: supersonic_db
  #     DB_USERNAME: supersonic_user
  #     DB_PASSWORD: supersonic_password
  #     CHROMA_HOST: supersonic_chroma
  #   depends_on:
  #     chroma:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ../..:/workspaces:cached
  #   ports:
  #     - "9080:9080"
  #   command: sleep infinity
  #   networks:
  #     - supersonic_network

  # supersonic_fe:
  #   build:
  #     context: .
  #     dockerfile: nodejs.20.Dockerfile
  #   ports:
  #     - "9000:9000"
  #   command: sleep infinity
  #   networks:
  #     - supersonic_network
  #   depends_on:
  #     - supersonic_be
  #   volumes:
  #     - ../:/workspace:cached
  
  chroma:
    image: chromadb/chroma:0.5.3
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma
    networks:
      - supersonic_network
    dns:
      - 114.114.114.114
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0:8000"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      LANG: 'C.UTF-8'
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: supersonic_db
      MYSQL_USER: supersonic_user
      MYSQL_PASSWORD: supersonic_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../launchers/standalone/src/main/resources/db/schema-mysql.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ../launchers/standalone/src/main/resources/db/data-mysql.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      - supersonic_network
    dns:
      - 114.114.114.114
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      chroma:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    image: ollama
    container_name: ollama
    environment:
      - LLM_MODEL=qwen:0.5b # qwen:0.5b is a small model, size is 352MB
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - supersonic_network
    healthcheck:
      test: ["CMD", "curl", "http://0.0.0.0:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
  chroma_data:
  ollama_data:

networks:
  supersonic_network: