spring:
  profiles:
    active: local
  application:
    name: chat
  config:
    import:
      - classpath:s2-config.yaml
      - classpath:langchain4j-config.yaml
  autoconfigure:
    exclude:
      - spring.dev.langchain4j.spring.LangChain4jAutoConfig
      - spring.dev.langchain4j.openai.spring.AutoConfig
      - spring.dev.langchain4j.ollama.spring.AutoConfig
      - spring.dev.langchain4j.azure.openai.spring.AutoConfig
      - spring.dev.langchain4j.azure.aisearch.spring.AutoConfig
      - spring.dev.langchain4j.anthropic.spring.AutoConfig

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml